---
# tasks file for web
- name: Install Nginx
  apt:
    name: nginx
    state: latest
  notify: restart nginx

- name: Install PHP-FPM
  apt:
    name: ['php8.0','php8.0-fpm', 'php8.0-mysql','php8.0-common','php8.0-cli','php8.0-curl', 'php8.0-simplexml', 'php8.0-mbstring', 'php8.0-zip', 'php8.0-imagick', 'php8.0-redis', 'php8.0-gd']
    state: latest

- name: Configure php.ini
  blockinfile:
    dest: /etc/php/8.0/fpm/php.ini
    block: |
      cgi-fix_pathinfo = 0
    backup: yes
  notify: restart php-fpm

- name: Set max upload size
  become: yes
  ini_file:
    path: /etc/php/8.0/fpm/php.ini
    section: PHP
    option: upload_max_filesize
    value: 10M
  notify: restart php-fpm

- name: Set max post size
  become: yes
  ini_file:
    path: /etc/php/8.0/fpm/php.ini
    section: PHP
    option: post_max_size
    value: 20M
  notify: restart php-fpm

- name: install composer
  get_url: url=https://getcomposer.org/installer dest=/tmp/composer-setup.php

- name: install composer globally
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

- name: Configure Horizon Supervisor
  supervisorctl:
    name: horizon
    state: present
