#!/bin/sh
#
# Configured as part of the Mailcoach 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the Mailcoach One-Click Install!
You can find more information and documentation
on https://mailcoach.app

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
